[platformio]
default_envs = part2

[env:part1]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<../lab01pt01.c>

[env:part2]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<../lab01pt2.c>
